# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0.xci
# IP: The module: 'system_rst_aurora_8b10b_0_156M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0.xci
# IP: The module: 'system_rst_aurora_8b10b_0_156M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_rst_aurora_8b10b_0_156M_0/system_rst_aurora_8b10b_0_156M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_aurora_8b10b_0_156M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
