# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1.xci
# IP: The module: 'system_v_vid_in_axi4s_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1.xci
# IP: The module: 'system_v_vid_in_axi4s_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/ZdunekPC/Documents/Spektrop2/Vivado/Spektrop2_CMV4000_V3/Spektrop2_CMV4000_V2.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
